apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hxh9n02fg-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hxh9n02fg-go 
  name: hxh9n02fg-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hxh9n02fg-go 
